name = "my-app"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
DATABASE_URL="postgres://postgres.jpvkhxwwtjwyjykzmenn:Fn8J2et+r@28Y~h@aws-0-ap-south-1.pooler.supabase.com:6543/postgres?pgbouncer=true"

 JWT_SECRET="testDBsecret"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

